### PR TITLE
fix: Don't use private DNS for VPC endpoints

### LINKED ISSUE #325: fix: cannot use apigateway lambdaAccess function with private dns names enabled
When you use a private dns name with the vpc endpoint the format for the api url needs to be  
`https://{rest-api-id}-{vpce-id}.execute-api.{region}.amazonaws.com/{stage}`

currently this will be set:
`https://{rest-api-id}.execute-api.{region}.amazonaws.com/{stage}`

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html#apigateway-private-api-route53-alias

### PR DESCRIPTION
**Pull request by kichik**
It affects the entire VPC. It also prevents us from having two of these endpoints in the same VPC. Finally, not all externally created endpoints will have private DNS enabled.

Fixes #325

### CODE REVIEW

File: src/access.ts [hunk 1]
```diff
@@ -244,6 +250,12 @@ class ApiGateway {
     // remove CfnOutput
     api.node.tryRemoveChild('Endpoint');
 
+    if (vpcEndpoint) {
+      // enabling private DNS affects the entire VPC, so we use the Route53 alias instead
+      // https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html
+      return `https://${api.restApiId}-${vpcEndpoint.vpcEndpointId}.execute-api.${region}.amazonaws.com/${api.deploymentStage.stageName}`;
```
Comment (pharindoko) [inline src/access.ts:256]: 👍

**Comment by pharindoko** [comment]
will try it out...
